apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
spec:
  controller: k8s.io/ingress-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv-apps-prod
spec:
  ingressClassName: nginx
  rules:
    - host: cc1fbde45ead-in-south-01.backstract.io
      http:
        paths:
          - path: /modest-jepsen-f74209c63f9211f095c5aec16983dee776/
            pathType: Prefix
            backend:
              service:
                name: coll-672169f28bf14be78de0a8b349bb3944-srv
                port:
                  number: 80
          - path: /practical-knuth-0eb2e3aa460011f080f2aec16983dee7100/
            pathType: Prefix
            backend:
              service:
                name: coll-73e8fe658da94aa3aa372a8cb5341958-srv
                port:
                  number: 80
          - path: /adoring-tara-df624b4a59a511f08548125b56bd792350/
            pathType: Prefix
            backend:
              service:
                name: coll-2fed9e9a2353488c81c2c9259ea64bf2-srv
                port:
                  number: 80
          - path: /stoic-rajat-6e51c34e589d11f0acec125b56bd792310/
            pathType: Prefix
            backend:
              service:
                name: coll-b4f0a5355bf548e1855b3c2258964843-srv
                port:
                  number: 80
          - path: /sad-joliot-fe3a4e6a58a511f082b9125b56bd792389/
            pathType: Prefix
            backend:
              service:
                name: coll-94fe21c2f72d4874ac70c9acfe7f3a0d-srv
                port:
                  number: 80
          - path: /festive-suresh-21726bfc5b3e11f0a279125b56bd792325/
            pathType: Prefix
            backend:
              service:
                name: coll-8bad4097c3364a3fae0fc9786e332e4b-srv
                port:
                  number: 80
          - path: /hardcore-visvesvaraya-007bfcd25d7911f0949e3adbebfba41066/
            pathType: Prefix
            backend:
              service:
                name: coll-455ba056408c4043ba38e7371b12f609-srv
                port:
                  number: 80
          - path: /optimistic-borg-737841b25c6d11f0a57f125b56bd792319/
            pathType: Prefix
            backend:
              service:
                name: coll-c91c749c0405484f99f2fade6f074431-srv
                port:
                  number: 80
          - path: /confident-jones-d00b9c5e5cc111f09405125b56bd792377/
            pathType: Prefix
            backend:
              service:
                name: coll-53765494976a4f5b86ae7ad25668d659-srv
                port:
                  number: 80
          - path: /interesting-stallman-246de1a85e1b11f0bdb63adbebfba41080/
            pathType: Prefix
            backend:
              service:
                name: coll-1ea27a104b204c968ae404fd13868280-srv
                port:
                  number: 80
          - path: /peaceful-diya-8da24468607611f0a70c3adbebfba41022/
            pathType: Prefix
            backend:
              service:
                name: coll-34cea5cb451d4b36a0d81448149da898-srv
                port:
                  number: 80
          - path: /heuristic-allen-bc1c26fc5b0211f08b7c125b56bd792364/
            pathType: Prefix
            backend:
              service:
                name: coll-a5946a091d1548a5a7a0eebbaea9f9b1-srv
                port:
                  number: 80
          - path: /suspicious-lakshmi-1bcc9aec5ca111f0972d125b56bd792391/
            pathType: Prefix
            backend:
              service:
                name: coll-736da61e135940bca43bd59ca133facf-srv
                port:
                  number: 80
          - path: /stoic-rekha-ef118cc65bc711f08f75125b56bd792381/
            pathType: Prefix
            backend:
              service:
                name: coll-117ac4e1d4af4501a5e220ae387227bd-srv
                port:
                  number: 80
          - path: /interesting-nobel-716ba8ec58a711f08a43125b56bd792329/
            pathType: Prefix
            backend:
              service:
                name: coll-90ef24e3b66742d7b913fa0f442835a8-srv
                port:
                  number: 80
          - path: /awesome-clarke-7aa4b982583c11f0b25c06b26b66b2c291/
            pathType: Prefix
            backend:
              service:
                name: coll-f2af154797c94f32abc57124dc4b70fa-srv
                port:
                  number: 80
          - path: /exciting-leela-21fba7d2624b11f098193adbebfba41061/
            pathType: Prefix
            backend:
              service:
                name: coll-7c7f0fca125c403cadb31ff42ce3f019-srv
                port:
                  number: 80
          - path: /flamboyant-mohan-eadc3aa6589e11f0adec125b56bd792357/
            pathType: Prefix
            backend:
              service:
                name: coll-a3c9abb261a34d328f00dd86153a97d1-srv
                port:
                  number: 80
          - path: /romantic-parvati-3ccaa0f058c211f0abb6125b56bd792324/
            pathType: Prefix
            backend:
              service:
                name: coll-63cccee346834badabb5c7f028ff4b33-srv
                port:
                  number: 80
          - path: /crazy-mirzakhani-6b0f966e5d4f11f08bc4125b56bd792383/
            pathType: Prefix
            backend:
              service:
                name: coll-cfc2f7d23e5d4d9b9df564d6517bbbf6-srv
                port:
                  number: 80
          - path: /cool-saha-62de01085e2411f09de83adbebfba41029/
            pathType: Prefix
            backend:
              service:
                name: coll-8ab4002b38a543e7ac20d89f278b9288-srv
                port:
                  number: 80
          - path: /charming-suman-320311e65be411f0b607125b56bd792313/
            pathType: Prefix
            backend:
              service:
                name: coll-f7b34085c9f4434eb5806d34facc5978-srv
                port:
                  number: 80
          - path: /eager-nisha-2e0b7bf4623e11f0b7073adbebfba41093/
            pathType: Prefix
            backend:
              service:
                name: coll-f50a5e1575014ca89bea8bc83a548531-srv
                port:
                  number: 80
          - path: /beautiful-aarav-a89d0804620e11f08b9d3adbebfba41011/
            pathType: Prefix
            backend:
              service:
                name: coll-6df35cf77b034366ab83f90549c01328-srv
                port:
                  number: 80
          - path: /sweet-knuth-07871c00630011f093403adbebfba4108/
            pathType: Prefix
            backend:
              service:
                name: coll-763816acc0f54481b35f2aa8ff64ebf0-srv
                port:
                  number: 80
          - path: /sweet-wilbur-e7549794630111f089653adbebfba41087/
            pathType: Prefix
            backend:
              service:
                name: coll-42cb0f59efba4ebc9f9df62db46c0d69-srv
                port:
                  number: 80
          - path: /cool-lumiere-ec31ca2e583a11f0a84e06b26b66b2c257/
            pathType: Prefix
            backend:
              service:
                name: coll-d5667c172c7d45079a4ec80623360a8e-srv
                port:
                  number: 80
          - path: /flamboyant-priyanka-87fb9f705c6911f083c9125b56bd792337/
            pathType: Prefix
            backend:
              service:
                name: coll-58848c1f1e534a24a2a16d1230ed6446-srv
                port:
                  number: 80
          - path: /eloquent-aditya-12a88646580611f08f88d6edd7103f1a45/
            pathType: Prefix
            backend:
              service:
                name: coll-666a57bf28ab46b48f05b522aaeab993-srv
                port:
                  number: 80
          - path: /hopeful-rupali-f79e9b2258a211f0b71c125b56bd792383/
            pathType: Prefix
            backend:
              service:
                name: coll-829599e115704e87890d3256c3342ef1-srv
                port:
                  number: 80
          - path: /romantic-mendel-4b9730e058cb11f08388125b56bd792369/
            pathType: Prefix
            backend:
              service:
                name: coll-622dfc3f9e264c698b0de45e57f4df88-srv
                port:
                  number: 80
          - path: /adoring-fermi-c5dd8efe5b3611f08b7b125b56bd792371/
            pathType: Prefix
            backend:
              service:
                name: coll-cb4b9022bcb449068d7ecdc0c671e638-srv
                port:
                  number: 80
          - path: /keen-kare-5db06c5c5cc111f0b6da125b56bd792331/
            pathType: Prefix
            backend:
              service:
                name: coll-97f398eb91d540509711cef97c607d76-srv
                port:
                  number: 80
          - path: /amazing-parvati-0447896e5d7211f082e03adbebfba4102/
            pathType: Prefix
            backend:
              service:
                name: coll-e91799f181d74979adac2eead23b5a60-srv
                port:
                  number: 80
          - path: /pedantic-wozniak-8c6ca636607311f0bfe63adbebfba41019/
            pathType: Prefix
            backend:
              service:
                name: coll-4f105e922f3e44beafbbbfb9663a33ea-srv
                port:
                  number: 80
          - path: /pensive-saha-da5d681e662511f0a8ad8204c7dc2e0526/
            pathType: Prefix
            backend:
              service:
                name: coll-4d5bf8770aa94b958920c5868fc54f97-srv
                port:
                  number: 80
          - path: /quizzical-vishal-c8811ab463be11f096a8aeb1eafad82716/
            pathType: Prefix
            backend:
              service:
                name: coll-50759ca12b0940539607d563e20439b2-srv
                port:
                  number: 80
          - path: /adoring-brown-42e88aac630c11f0ab6e3adbebfba41012/
            pathType: Prefix
            backend:
              service:
                name: coll-ab363c6f64054d3a839823d3df9f075a-srv
                port:
                  number: 80
          - path: /mystifying-bharati-2638fe5663ba11f09ff7aeb1eafad82710/
            pathType: Prefix
            backend:
              service:
                name: coll-bd075863fcc046b1a54bd5b6770ff2e8-srv
                port:
                  number: 80
          - path: /pensive-aditya-6be7f9906a3411f0b36406f8555b529d50/
            pathType: Prefix
            backend:
              service:
                name: coll-f4f1b77b33d7481ba90d8fed6294c782-srv
                port:
                  number: 80
          - path: /beautiful-vaishali-94a123ec639111f0a63b3adbebfba41052/
            pathType: Prefix
            backend:
              service:
                name: coll-a434b6b314a24ca684d7a45c21ff1596-srv
                port:
                  number: 80
          - path: /cool-roentgen-95db697a641311f0b3488204c7dc2e0514/
            pathType: Prefix
            backend:
              service:
                name: coll-2a35bb244ee445ec8835984d55a04689-srv
                port:
                  number: 80
          - path: /competent-clarke-fd66303a63cc11f09d0e8204c7dc2e0546/
            pathType: Prefix
            backend:
              service:
                name: coll-eef40991ffc542cc975261a632207c73-srv
                port:
                  number: 80
          - path: /competent-rahul-05707b126a3711f0803606f8555b529d44/
            pathType: Prefix
            backend:
              service:
                name: coll-10cc5831a55c403d96e28209f3564246-srv
                port:
                  number: 80
          - path: /beautiful-savita-09913100692411f0a1f88204c7dc2e0532/
            pathType: Prefix
            backend:
              service:
                name: coll-35433430dcef47f694851de23213aee2-srv
                port:
                  number: 80
          - path: /reverent-hugle-833ebe246b7b11f0adea265f29b63e2f24/
            pathType: Prefix
            backend:
              service:
                name: coll-37f42074ba5f4ae7b9573dc220bbff10-srv
                port:
                  number: 80
          - path: /clever-sita-a3e156ac6b9711f0b48e265f29b63e2f50/
            pathType: Prefix
            backend:
              service:
                name: coll-c9329aeebe644939abefe18b28c4c0d6-srv
                port:
                  number: 80
          - path: /charming-aditya-7e0dd1e46d1311f093fc063a1e80bfcf5/
            pathType: Prefix
            backend:
              service:
                name: coll-a4df2a989ac6430895d83b75667cb6b4-srv
                port:
                  number: 80
          - path: /eager-mclean-40b81a48729f11f08befb2a3596eee1c36/
            pathType: Prefix
            backend:
              service:
                name: coll-cee72c0d11a340349fb9402c78d85089-srv
                port:
                  number: 80
          - path: /modest-gauri-55f3f3be6b8311f0b68d265f29b63e2f74/
            pathType: Prefix
            backend:
              service:
                name: coll-16e4cd0318d348b29da3a3678ca92215-srv
                port:
                  number: 80
          - path: /naughty-kirch-abeec82c6b8611f0a833265f29b63e2f13/
            pathType: Prefix
            backend:
              service:
                name: coll-f23199e85f4c4add9eaaf22bb3510794-srv
                port:
                  number: 80
          - path: /trusting-montalcini-42a8c9126d1611f0b197063a1e80bfcf41/
            pathType: Prefix
            backend:
              service:
                name: coll-fed44953a48a42aa8c938935d41bf96f-srv
                port:
                  number: 80
          - path: /relaxed-galois-ea5aea8a6c8711f0974622bcffa0f4d722/
            pathType: Prefix
            backend:
              service:
                name: coll-22db355d387a4f2fbacaf363965c7516-srv
                port:
                  number: 80
          - path: /suspicious-sagar-444b599a6b9c11f080238e67364f310019/
            pathType: Prefix
            backend:
              service:
                name: coll-9ba78540f53d4c2784e9724d19416e09-srv
                port:
                  number: 80
          - path: /stupefied-kiran-d6e9970672c411f0a962e237aac79c5626/
            pathType: Prefix
            backend:
              service:
                name: coll-5d9f9351d09a480da057e6b6c4be8565-srv
                port:
                  number: 80
          - path: /friendly-goldstine-9b5c3aec6df411f08f13961bb727fd5785/
            pathType: Prefix
            backend:
              service:
                name: coll-cdbb1621cd3c4b059bf372446b8ba78f-srv
                port:
                  number: 80
          - path: /gifted-brattain-136e7adc6c5a11f086b7e6b73f1f222d91/
            pathType: Prefix
            backend:
              service:
                name: coll-f84f74ad2a2a480f885626afa8a69f07-srv
                port:
                  number: 80
          - path: /exciting-vihaan-9a538e3a6d2b11f09d93063a1e80bfcf2/
            pathType: Prefix
            backend:
              service:
                name: coll-3fe50bfddbe84bd4a9f047084453f64d-srv
                port:
                  number: 80
          - path: /clever-wescoff-89e8185a6ec911f09bcf961bb727fd5746/
            pathType: Prefix
            backend:
              service:
                name: coll-5397b12f7d9f4231b301414f53cc051e-srv
                port:
                  number: 80
          - path: /pensive-burnell-500ee3d872a311f08694b2a3596eee1c38/
            pathType: Prefix
            backend:
              service:
                name: coll-09cd017d9ac340c2a29f23001800fced-srv
                port:
                  number: 80
          - path: /practical-lewin-6fed46d4735411f0be7ce237aac79c5610/
            pathType: Prefix
            backend:
              service:
                name: coll-3d7ac5b3ff374279900d74b477fd12b3-srv
                port:
                  number: 80
          - path: /boring-hoover-f6d447d4736211f0bbfee237aac79c5642/
            pathType: Prefix
            backend:
              service:
                name: coll-a260ac3ea6b94472b19d31845a69face-srv
                port:
                  number: 80
          - path: /bold-brahmagupta-38cff8fe737211f095b8e237aac79c5667/
            pathType: Prefix
            backend:
              service:
                name: coll-1aad5b344cba4da3ad312bc7d98b9326-srv
                port:
                  number: 80
          - path: /naughty-poincare-f73b7e72743e11f08d4de237aac79c5614/
            pathType: Prefix
            backend:
              service:
                name: coll-8428360e75564a909f6f8f2aa146591f-srv
                port:
                  number: 80
          - path: /laughing-priyanka-ef06884c737f11f08840e237aac79c5643/
            pathType: Prefix
            backend:
              service:
                name: coll-4cd98a0d880745f3b056b08a644e70fa-srv
                port:
                  number: 80
          - path: /elegant-ananya-a1f4b902738e11f08c15e237aac79c5657/
            pathType: Prefix
            backend:
              service:
                name: coll-6d822c63420e4dc284e198d579b45f79-srv
                port:
                  number: 80
          - path: /dreamy-aishwarya-b656cf3c739011f0999be237aac79c5637/
            pathType: Prefix
            backend:
              service:
                name: coll-67c7a7dad4c9421e99c17da1601e22b5-srv
                port:
                  number: 80
          

